### PR TITLE
Fix order cancellation process

### LINKED ISSUE #114: Cancelar pedido
Implementar a funcionalidade de Cancelar pedido.

São as mesmas regras de negócio dessa issue: https://github.com/ufersa/plataforma-sabia/issues/483

### PR DESCRIPTION
**Pull request by mtullyoc**
## Summary

Resolves #114 

https://user-images.githubusercontent.com/17722915/119473333-72a63e00-bd21-11eb-84d3-e90982553a29.mov

### CODE REVIEW

File: src/screens/RequestsDetails/index.tsx [hunk 1]
```diff
@@ -142,38 +129,114 @@ const RequestsDetails = ({ route: { params } }: RequestsDetailsProps): JSX.Eleme
                 </S.OpenChat>
               </S.Detail>
             </S.CardDetails>
-            {status === 'open' && (
+            {(status === 'open' || status === 'requested') && (
```
Comment (mateus4k) [inline src/screens/RequestsDetails/index.tsx]:
```suggestion
            {['open', 'requested'].includes(status) && (
```

**Review by mateus4k — APPROVED** [review]

**Review by davioliveiira — APPROVED** [review]
